pull_request_rules:
  - name: Prepare pull request to be merge
    conditions:
      - base=main
      - -draft
      - -merged
      - -closed
      - label!=do-not-merge
      - label=simulate-approvals # simulate
    actions:
      comment:
        message: Thank you for contributing! Your pull request is now being automatically merged.
      label:
        add:
          - ci-queued
      # queue:
      #   method: squash
  - name: Automatic merge on approval
    conditions:
      - base=main
      - -draft
      - -merged
      - -closed
      - label!=do-not-merge
      - label=ci-queued
      - check-success=CI Status
    # label:
    #   remove:
    #     - ci-merge
    actions:
      merge:
        method: squash
  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.
  - name: warn on conflicts
    conditions:
      - conflict
      - -draft
      - -merged
      - -closed
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - ci-conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
      - -draft
      - -merged
      - -closed
    actions:
      label:
        remove:
          - ci-conflict
