name: Apply Release Plan

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

concurrency:
  group: 'apply-release-plan'
  cancel-in-progress: false

jobs:
  print-info:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-queued') &&
      github.event.pull_request.state == 'open' &&
      github.actor == 'mergify[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Print info
    steps:
      - name: Print info
        run: |
          echo "actor: ${{ github.actor }}"
          echo "pr state: ${{ github.event.pull_request.state }}"
          echo "labels: ${{ github.event.pull_request.labels }}"
  apply-release-plan:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-queued') &&
      github.event.pull_request.state == 'open' &&
      github.actor == 'mergify[bot]'
    needs: [print-info]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Apply Release Plan
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      # - name: Remove labels
      #   continue-on-error: true
      #   uses: actions-ecosystem/action-remove-labels@v1
      #   with:
      #     labels: |
      #       ci-merge-prepare
      #     github_token: ${{ secrets.ACTION_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
        with:
          version: 7.9.5
      - name: Setup git
        run: |
          git fetch --no-tags --prune --depth=5 origin main:main
          git config --global user.email "bot@soundstep.com"
          git config --global user.name "soundstep-bot"
      - name: Cache workspace
        id: cache-workspace
        uses: ./.github/actions/ci/workspace-cache
      - name: Apply release plan
        run: |
          ./.github/actions/ci/release-plan-apply.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      - name: Save pnpm store to cache
        if: steps.cache-workspace.outputs.pnpm-store-hit != 'true'
        uses: martijnhols/actions-cache/save@b4759b598f97eb31dbd72627b610d83b85c87c97
        with:
          path: ~/.pnpm-store
          key: ${{ steps.cache-workspace.outputs.pnpm-store-key }}
  set-pending-status:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-queued') &&
      github.event.pull_request.state == 'open' &&
      github.actor == 'mergify[bot]'
    needs: [apply-release-plan]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Set pending status
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set penging status
        run: |
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "CURRENT_SHA: $CURRENT_SHA"
          curl --location --request POST "https://${{ secrets.ACTION_TOKEN }}@api.github.com/repos/${{ github.repository }}/statuses/$CURRENT_SHA" \
            --header 'Accept: application/vnd.github.antiope-preview+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "state": "pending",
                "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "description": "Running...",
                "context": "CI Status"
            }'
  # merge-branch:
  #   needs: [set-pending-status]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   name: Merge Branch
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.head_ref }}
  #         fetch-depth: 0
  #     - name: Merge Pull Request
  #       uses: juliangruber/merge-pull-request-action@v1
  #       with:
  #         github-token: ${{ secrets.ACTION_TOKEN }}
  #         number: ${{ github.event.number }}
  #         method: squash
  set-error-status:
    if: |
      contains(github.event.pull_request.labels.*.name, 'ci-queued') &&
      github.event.pull_request.state == 'open' &&
      github.actor == 'mergify[bot]' &&
      (needs.apply-release-plan.result == 'failure' || needs.merge-branch.result == 'failure')
    # needs: [apply-release-plan, merge-branch]
    needs: [apply-release-plan]
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Set error status
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set error status
        run: |
          CURRENT_SHA=$(git rev-parse HEAD)
          echo "CURRENT_SHA: $CURRENT_SHA"
          curl --location --request POST "https://${{ secrets.ACTION_TOKEN }}@api.github.com/repos/${{ github.repository }}/statuses/$CURRENT_SHA" \
            --header 'Accept: application/vnd.github.antiope-preview+json' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "state": "error",
                "target_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                "description": "Running...",
                "context": "CI Status"
            }'
