name: Print
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [labeled]

concurrency:
  group: 'print-info'
  cancel-in-progress: false

jobs:
  print:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Print information
    steps:
      - name: Print
        run: |
          echo "actor: ${{ github.actor }}"
